backend = "glx";
vsync = true;
glx-use-copysubbuffer-mesa = true;

glx-copy-from-front = true;
glx-swap-method = 2;
xrender-sync = true;
xrender-sync-fence = true;


# Rounded Corners
corner-radius = 12;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "class_g = 'Polybar'"
];