color_theme = "catppuccin_mocha"
theme_background = false
proc_tree_view = false
proc_info = true
proc_gradient = true
proc_per_core = false
proc_reversed = false
proc_sorting = "cpu lazy"
proc_filter = ""
proc_foreground = true
proc_depth = 0
proc_highlight = true
proc_show_docker = true
cpu_graph_upper = 100
cpu_graph_lower = 0
cpu_invert_lower = false
cpu_single_graph = false
cpu_graph_operator = "average"
show_uptime = true
show_swap = true
show_io_stat = true
show_io_mode = false
show_disks = true
show_sensors = false
show_cmdline = true
show_clock = true
update_ms = 2000
