[manager]
ratio = [1, 3, 4]
show_hidden = false
sort_by = "natural"
sort_dir_first = true
linemode = "none"

[preview]
max_width = 600
max_height = 900
cache_dir = "/tmp/yazi"

[opener]
edit = [
  { run = 'nvim "$@"', desc = "Neovim" },
]
open = [
  { run = 'xdg-open "$@"', desc = "System default" },
]
